HouseworkModels/Controler/Converter
pprochot/RoomMe pull request #22
Opened 2022-01-11 21:35 UTC by march5

2022-01-16 12:56 UTC, mateuszbasiak requested changes
Komentarze do poprawki

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +                            .FirstOrDefaultAsync(x => x.Id == houseworkId)
FindAsync tutaj mozesz uzyc jezeli sie nie myle

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            }*/
Komentarze usuwamy - nie chcemy ich na devie

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/SchedulePutReturnModel.cs
> +        public int Id { get; set; }
TimeStampa mozesz tutaj dodac

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/SchedulePutModel.cs
> +        public int StatusId { get; set; }
Tego nie chcemy przekazywac - logiką tej kolumny będzie zajmować się backend a nie użytkownik

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/ScheduleFullGetModel.cs
> +        public int StatusId { get; set; }
Nie musisz przekazywac statusId bo on jest juz w modelu status

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/ScheduleFullGetModel.cs
> +        public int SettingsId { get; set; }
Tak samo tutaj - id już w settings

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/ScheduleFullGetModel.cs
> +        public int HouseworkId { get; set; }
To id też niepotrzebne

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/HouseworkSettingsModel.cs
> +        public int HouseworkId { get; set; }
Nie dodawaj do takich modeli housework

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/HouseworkSettingsPutModel.cs
> +        public HouseworkNameModel Housework { get; set; }
Tego nie musisz przekazywac

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/ScheduleHouseworkNameModel.cs
> +    public class ScheduleHouseworkNameModel
Po co ten model?

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +            var status = await _sqlContext.HouseworkStatuses.FindAsync(schedule.StatusId).ConfigureAwait(false);
Tak jak wspominałem - ta część musi być wykonana inaczej. Zaproponuj statusy jakie mogą być i nastepnie ustawiaj tutaj początkowy

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/ScheduleConverter.cs
> +                User = user,
Nie musisz tego ustawiac - przekaz sam userId i ef core sobie poradzi. Dzieki temu nie bedziemy musieli pobierac usera z bazy

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/ScheduleConverter.cs
> +                Id = schedule.Id
Timestamp

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +        [HttpGet("{scheduleId}/full", Name = nameof(GetScheduleFull))]
Dlaczego masz dwa razy tą samą ścieżke? Do poprawy

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +                .Include(x => x.StatusId)
Status

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +                .Include(y => y.HouseworkSettings.Id)
HouseworkSettings

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +                .FirstOrDefaultAsync(x => x.Id == scheduleId)
FindAsync można chyba użyć

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +        public async Task<ActionResult<HouseworkNameModel>> GetHouseworkName(int houseworkId)
Raczej chcemy miec cos do pobierania listy zadan z danego okresu czasu - nie widze jak moglibysmy tego endpointa uzyc

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            List<User> users = new();
Po co ta lista?

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +                var entity = await _sqlContext.Users.FindAsync(userId).ConfigureAwait(false);
Sprawdzaj istnienie użytkownika za pomocą any

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            var author = await _sqlContext.Users.FindAsync(housework.AuthorId).ConfigureAwait(false);
Tu tak samo

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            var flat = await _sqlContext.Flats.FindAsync(housework.FlatId).ConfigureAwait(false);
Tu tak samo

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            author.Houseworks.Add(housework.ToHouseworkModel(author, flat, users));
To nie zadziała - dodaj nowego houseworka - nawigacje i klucze obce automatyczne sie zaktualizuja

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            flat.Houseworks.Add(housework.ToHouseworkModel(author, flat, users));
Jak zrobisz to wyzej to to niepotrzebne

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            _sqlContext.Update(flat);
Wtedy _sqlContext.AddAsync(housework)

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            foreach(var entity in users)
To jest niepotrzebne

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            await _sqlContext.Houseworks.AddAsync(houseworkEntity).ConfigureAwait(false);
Skoro to masz, to te powyższe updaty nie są potrzebne

2022-01-16 12:56 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +            author.Houseworks.Add(housework.ToHouseworkModel(author, flat, users));
EDIT: masz to nizej, wiec do usuniecia

2022-01-16 21:09 UTC, march5 commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +                .FirstOrDefaultAsync(x => x.Id == scheduleId)
Chyba nie ma opcji użycia FindAsync

2022-01-16 21:09 UTC, march5 commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +                            .FirstOrDefaultAsync(x => x.Id == houseworkId)
Chyba nie da się tutaj FindAsync

2022-01-17 00:24 UTC, mateuszbasiak requested changes

2022-01-17 00:24 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/ScheduleFullGetModel.cs
> +        public int HouseworkId { get; set; }
Info o housework tutaj by sie tez przydalo

2022-03-03 11:58 UTC, mateuszbasiak requested changes

2022-03-03 11:58 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +        public async Task<ActionResult<HouseworkFrequencyModel>> GetSettingsFrequency(int settingsId)
W linku masz houseworkId a w ogole z niego nie korzystasz?

2022-03-03 11:58 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +        public async Task<ActionResult<HouseworkSettingsModel>> GetHouseworkSettings(int settingsId)
Nie masz w linku settingsId tylko houseworkId

2022-03-03 11:58 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +        public async Task<ActionResult<List<HouseworkFullGetModel>>> GetFullHouseworkByDate(FromToDateModel dates)
To Ci dziala? Powinno rzucac bledem ze GET nie moze miec body

2022-03-03 12:00 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +        public async Task<ActionResult<List<HouseworkFullGetModel>>> GetFullHouseworkByDate(FromToDateModel dates)
Dodatkowo: to jeszcze powinno byc filtrowane po mieszkaniu - chcemy miec tylko prace z jednego mieszkania

2022-03-03 12:01 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +                _logger.LogError($"Housework not found for id {settingsId}");
Zmien blad na bardziej czytelny, bo aktualnie wprowadza w blad

2022-03-06 19:48 UTC, mateuszbasiak requested changes

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +            scheduleEntity.HouseworkStatus = status;
Tych 2 linijek wyzej nie musisz dodawac po tym jak ustawiles juz statusId na 1

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +            return schedulesModels;
Zwróć po prostu schedules.Select(x => x.ToScheduleDateModel()).ToList()

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +        public async Task<ActionResult<List<ScheduleFullGetModel>>> GetFullSchedulesByDate([FromQuery] FromToDateModel dates, int houseworkId)
Tu chciałbym, zebysmy zwracali uproszczone info zamiast całego, wyobrazam sobie ze to ma nam posluzyc do tworzenia odpowiednich obiektow do kalendarza (na pewno Id, nazwa, data, status i moze id i nazwa uzytkownika)

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/HouseworkConverter.cs
> +            houseworkEntity.AuthorId = 1;
Mamy autentykacje juz do tego - zmerguj z masterem brancha i sprobuj odtworzyc to tak jak w FlatController (w razie pytan pisz smialo)

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/HouseworkConverter.cs
> +            houseworkEntity.AuthorId = 1;
Takie tldr: mamy sessionHelper ktory moze nam zwrocic Id aktualnie zalogowanego uzytkownika

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +    [ApiController]
Dodaj atrybut Authorize

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +    [ApiController]
Dodaj atrybut Authorize

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +    public class ScheduleController
Controller niech dziedziczy po klasie ControllerBase

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
> +    public class HouseworkController
Klasa kontrolera niech dziedziczy po ControllerBase

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/HouseworkConverter.cs
> +                AuthorId = 1,
Mamy autoryzacje juz - za pomoca sessionHelpera bedziesz mogl to wyciagnac po zmergowaniu deva

2022-03-06 19:48 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/ScheduleConverter.cs
> +                //TODO: UserId received through JWT token
???

2022-03-23 17:16 UTC, mateuszbasiak approved these changes

2022-03-23 17:16 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Converters/HouseworkConverter.cs
> +                AuthorId = 1,
To nie zostało zmienione?

2022-03-23 17:16 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.SQLContext/Dictionaries/HouseworkFrequencyDictionary.cs
> +		public static void AddRecords(ModelBuilder modelBuilder)
Popraw wciecie

2022-03-23 17:16 UTC, merged