Housework refactor
pprochot/RoomMe pull request #41
Opened 2022-04-26 21:01 UTC by mateuszbasiak

2022-04-28 17:02 UTC, pprochot commented on Backend/RoomMe/RoomMe.API/Models/HouseworkPostModel.cs
> +        public int[] Days { get; set; }
Czemu tablica, a nie lista?

2022-04-28 17:03 UTC, pprochot commented on Backend/RoomMe/RoomMe.API/Models/HouseworkSettingsModel.cs
> +        public int[] Days { get; set; }
Tutaj tez

2022-05-01 11:43 UTC, pprochot commented
@mateuszbasiak potrzebny jest endpoint do pobierania wszystkich houseworków

2022-05-03 21:51 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/HouseworkPostModel.cs
> +        public int[] Days { get; set; }
To nie ma znaczenia - to i to tak samo zostanie przeparsowane

2022-05-03 21:51 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/HouseworkSettingsModel.cs
> +        public int[] Days { get; set; }
Jak wyżej

2022-05-03 21:52 UTC, mateuszbasiak commented on Backend/RoomMe/RoomMe.API/Models/HouseworkPostModel.cs
> +        public int[] Days { get; set; }
To nie ma zadnej roznicy - sam model bedzie wygladal tak samo w obu przypadkach

2022-05-07 12:30 UTC, pprochot requested changes
@mateuszbasiak Usuń dwa endpointy które zaznaczyłem i chyba będzie można mergować

2022-05-07 12:30 UTC, pprochot commented on Backend/RoomMe/RoomMe.API/Controllers/HouseworkController.cs
>          [HttpGet("{houseworkId}/settings", Name = nameof(GetHouseworkSettings))]
Można usunąć endpoint

2022-05-07 12:30 UTC, pprochot commented on Backend/RoomMe/RoomMe.API/Controllers/ScheduleController.cs
> +        public async Task<ActionResult<SchedulePostReturnModel>> CreateNewSchedule(SchedulePostModel schedule)
Można usunąć endpoint

2022-05-14 14:48 UTC, pprochot commented on Backend/RoomMe/RoomMe.API/Controllers/FlatController.cs
> +            if(flat == null || _sessionHelper.IsCreatorOfFlat(flat))
powinno być `!_sessionHelper.IsCreatorOfFlat(flat)`

2022-05-15 21:15 UTC, pprochot approved these changes

2022-05-16 08:21 UTC, pprochot commented on Backend/RoomMe/RoomMe.API/Models/HouseworkModel.cs
> +        public ScheduleShortModel NextSchedule { get; set; }
Zmień na ScheduleModel

2022-05-17 19:25 UTC, merged