Ios app
pprochot/RoomMe pull request #53
Opened 2022-06-17 18:09 UTC by c-44h

2022-06-17 18:17 UTC, pprochot commented on ios-app/RoomMe/RequestSender.swift
> +    func postRequest(path: String, body: Dictionary<String, Any>) -> String {
Pousuwajcie taki zakomentowany kod

2022-06-17 18:18 UTC, mateuszbasiak requested changes

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/LoginView.swift
> +                               }*/
Comments to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/NewFlatView.swift
> +*/
Comments to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/NewFrienfView.swift
> +            //print(exists)
to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/NewHouseworkView.swift
> +            //print(exists)
to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/NewRoommateView.swift
> +            //print(exists)
to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/RequestSender.swift
> +    }*/
comments to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/TaskView.swift
> +                                .cornerRadius(40)*/
Comments to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/AddListItemsView.swift
> +*/
Comments to remove

2022-06-17 18:18 UTC, mateuszbasiak commented on ios-app/RoomMe/LittleHomeView.swift
> +            //Spacer()
to remove

2022-06-22 11:25 UTC, mateuszbasiak approved these changes

2022-06-22 11:26 UTC, merged